# Generated by Django 3.2.5 on 2021-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0004_auto_20210916_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=264, unique=True),
        ),
    ]
